name: Java CI
on:
  push:
    tags:
      - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      
    - name: Build with Gradle
      run: ./gradlew -Pversion=$RELEASE_VERSION clean build
    - name: Create Jar Pack
      run: pack200 --no-gzip launcher.jar.pack launcher/build/libs/launcher-$RELEASE_VERSION-all.jar
      
    - name: Upload launcher to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: launcher/build/libs/launcher-$RELEASE_VERSION-all.jar
        asset_name: launcher-$RELEASE_VERSION-all.jar
        tag: ${{ github.ref }}
        overwrite: true
